config/routes.rb
PostEcpal::Application.routes.draw do
  resources :orders

match 'abc' => 'abc#index'

end

app/models/order.rb
class Order < ActiveRecord::Base
  attr_accessible :id, :order_date, :order_number, :status, :total
  
  STATUS_PENDING = "0001";
  STATUS_SHIPPING = "0002";
  STATUS_SHIPPED = "0003";
  STATUS_RETURNED = "0004";
  STATUS_CANCELED = "0005";
  STATUS_CLOSED = "0006";
  
  STATUS = {
    STATUS_PENDING => "pending",
    STATUS_SHIPPING => "shipping",
    STATUS_SHIPPED => "shippped",
    STATUS_RETURNED => "returned",
    STATUS_CANCELED => "cancel",
    STATUS_CLOSED => "closed"
  }
end

app/controllers/abc_controller.rb
class AbcController < ApplicationController
  def index
    @orders = Order.all
    render :xml => @orders
  end
end

app/controllers/application_controller.rb
require 'fluent-logger'
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  def log(tag, json)
    json["ip"] = request.remote_ip
    Fluent::Logger::FluentLogger.open(nil, :host=>Rails.application.config.fluent_host, :port=>Rails.application.config.fluent_port)
    Fluent::Logger.post(tag, json)
  end
  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
    respond_to do |format|
      format.html # index.html.erb
      format.json {
        log("mongo.logs", {"action"=> "user get orders list"}) 
        render json: @orders 
      }
    end
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @order = Order.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/new
  # GET /orders/new.json
  def new
    @order = Order.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @order }
    end
  end

  # GET /orders/1/edit
  def edit
    @order = Order.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(params[:order])

    respond_to do |format|
      if @order.save
        log("mongo.logs", {"action"=> "user create order", "order_number" => @order.order_number, "order_id" => @order.id})
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render json: @order, status: :created, location: @order }
      else
        format.html { render action: "new" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /orders/1
  # PUT /orders/1.json
  def update
    @order = Order.find(params[:id])

    respond_to do |format|
      if @order.update_attributes(params[:order])
        log("mongo.logs", {"action"=> "user update order", "order_number" => @order.order_number, "order_id" => @order.id})
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render json: @order }
      else
        format.html { render action: "edit" }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order = Order.find(params[:id])
    log("mongo.logger", {"action"=> "user remove order", "order_number" => @order.order_number, "order_id" => @order.id})
    @order.destroy

    respond_to do |format|
      format.html { redirect_to orders_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostEcpal</title>
  <%= stylesheet_link_tag :style %>
  <%= stylesheet_link_tag 'cupertino/jquery-ui-1.7.3.custom' %>
  <%= javascript_include_tag "json2" %>
  <%= javascript_include_tag "jquery-min" %>
  <%= javascript_include_tag "serialize-object" %>
  <%= javascript_include_tag "underscore" %>
  <%= javascript_include_tag "backbone" %>
  <%= javascript_include_tag 'jquery-ui-1.7.3.custom.min.js' %>
  <%= csrf_meta_tags %>
</head>
    
<body>
<div id="wrapper">
    <div id="content">
        <%= yield %>
    </div>
</div>
</body>
</html>

app/views/orders/_form.html.erb
<%= form_for(@order) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br />
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :order_number %><br />
    <%= f.text_field :order_number %>
  </div>
  <div class="field">
    <%= f.label :order_date %><br />
    <%= f.date_select :order_date %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :total %><br />
    <%= f.number_field :total %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing order</h1>

<%= render 'form' %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<h1>Listing orders</h1>
<div id="order-view">
<form>
<table id="table-list" cellspacing="0">
    <thead>
  <tr>
    <th><input type="checkbox" id="toggle-all"/></th>
    <th>Order number</th>
    <th>Order date</th>
    <th>Status</th>
    <th>Total</th>
    <th>Action</th>
  </tr>
  </thead>
   <tbody>
   </tbody>
</table>
<br />

<input type="button" value="New Order" id="new-order"/>
<input type="button" value="Delete" id="delete-order"/>
<div id="order-form-view">

</div>
</div>
</form>

<script type="text/template" id="order-item-template">
    <td class="center"><input type="checkbox" value="<@= id @>" class="cb-order"/></td>
    <td class="order_number"><@= order_number @></td>
    <td class="center order_date"><@= order_date @></td>
    <td><select class="status">
        <@ _.each(status_options, function(text, value) { @>
            <option value="<@= value @>" <@= (status == value)? 'selected="selected"' : '' @>><@= text @></option>
        <@ }); @>
    </select></td>
    <td class="right total"><@= total @></td>
    <td class="right"><a href="javascript:void(0);" class="edit-order">Edit</a>&nbsp;|&nbsp;<a href="javascript:void(0);" class="remove-order">Remove</a></td>
</script>

<script type="text/template" id="order-form-template">
    <legend><@= (is_new)? 'New': 'Edit' @> Order</legend>
    <form id="order-form">
        <table id="table-form">
            <tr>
                <th><label>Order Number</label></th>
                <td><input type="text" class="order_number" name="order_number" value="<@= order_number @>"/></td>
            </tr>
            <tr>
                <th><label>Order Date</label></th>
                <td><input type="text" class="order_date" name="order_date" value="<@= order_date @>"/></td>
            </tr>
            <tr>
                <th><label>Status</label></th>
                <td><select class="status" name="status">
                    <@ _.each(status_options, function(text, value) { @>
                        <option value="<@= value @>" <@= (status == value)? 'selected="selected"' : '' @>><@= text @></option>
                    <@ }); @>
                </select></td>
            </tr>
            <tr>
                <th><label>Total</label></th>
                <td><input type="text" class="total" name="total" value="<@= total @>"/></td>
            </tr>
         </table>
         <input type="button" id="update-order" value="<@= (is_new)? 'Create': 'Update' @> Order"/>
     </form>
</script>
<script type="text/javascript">
    var status_options = <%= raw Order::STATUS.to_json %>;
    
    var OrderModel = Backbone.Model.extend({
        urlRoot: '/orders',
        defaults: {
            id: null,
            order_number: "",
            order_date: (new Date()).getFullYear() + "-" + ((new Date()).getMonth() + 1) + "-" + (new Date()).getDate(),
            status: "<% Order::STATUS_PENDING %>",
            total: 0
        }
    });
    
    var OrderList = Backbone.Collection.extend({
        model: OrderModel,
        url: '/orders'
    });
    
    Orders = new OrderList();
    
    var OrderView = Backbone.View.extend({
        events: {
            "change select": "changeStatus",
            "click .edit-order": "editOrder",
            "click .remove-order": "removeOrder"

        },
        initialize: function(){
            //this.model.on('change', this.test, this);
            this.model.on('destroy', this.remove, this);
            this.model.on('sync', this.render, this);
        },
        template: _.template($('#order-item-template').html()),
        tagName: 'tr',
        render: function(){
            this.$el.html(this.template(this.model.toJSON())); 
        },
        remove: function(){
           this.$el.remove(); 
        },
        changeStatus: function(e){
            value = this.$(".status").val();
            this.model.save({status: value});
        },
        editOrder: function(){
            var order_form_view = new OrderFormView({model: this.model});
            $("#order-form-view").html(order_form_view.el);
            $("#order-form-view .order_date").datepicker({dateFormat: 'yy-mm-dd'});
        },
        removeOrder: function(){
            if (confirm("Do you want to delete this orders?")){
                this.model.destroy();
            }
        }
    });
    
    var OrderFormView = Backbone.View.extend({
        events: {
            'click #update-order': "saveOrder"
        },
        initialize: function(){
            this.model.set({is_new: this.model.isNew()});
            this.model.on('sync', this.saveSuccess, this);
            this.render();
        },
        tagName: 'fieldset',
        template: _.template($('#order-form-template').html()),
        render: function(){
            this.$el.html(this.template(this.model.toJSON()));
        },
        saveOrder: function(){
            var data = this.$("form").serializeObject();
            this.model.save(data);
        },
        saveSuccess: function(){
            if (this.model.get('is_new')){
                Orders.add(this.model);
            }
            this.remove();
        }
    });
    
    var AppView = Backbone.View.extend({
        el: $("#order-view"),
        
        events: {
            "click #toggle-all": "selectAll",
            "click #new-order": "newOrder",
            "click #delete-order": "deleteOrders"
        },
        
        initialize: function(){
            this.new_order = this.$("#new-order");
            this.all_checkbox = this.$("#toggle-all");
            
            Orders.on('add', this.addOne, this);
            Orders.on('reset', this.addAll, this);
            
            Orders.fetch();
        },
        addOne:function(orderItem){
            order_view = new OrderView({model: orderItem});
            order_view.render();
            this.$("#table-list tbody").append(order_view.el);
        },
        addAll: function(){
            Orders.each(this.addOne);
        },
        selectAll: function(){
            if (this.all_checkbox.attr("checked")){
                this.$(".cb-order").attr("checked", "true");
            } else {
                this.$(".cb-order").removeAttr("checked");
            }
        },
        newOrder: function(){
            var order_model = new OrderModel();
            var order_form_view = new OrderFormView({model: order_model});
            this.$("#order-form-view").html(order_form_view.el);
            $("#order-form-view .order_date").datepicker({dateFormat: 'yy-mm-dd'});
        },
        deleteOrders: function(){
            if (confirm("Do you want to delete the selected orders?")){
                this.$(".cb-order:checked").each(function(i, e){
                    var order_model = Orders.get($(e).val());
                    order_model.destroy();
                });
            }
        }
    });
    
    new AppView();
    
</script>

app/views/orders/new.html.erb
<h1>New order</h1>

<%= render 'form' %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Id:</b>
  <%= @order.id %>
</p>

<p>
  <b>Order number:</b>
  <%= @order.order_number %>
</p>

<p>
  <b>Order date:</b>
  <%= @order.order_date %>
</p>

<p>
  <b>Status:</b>
  <%= @order.status %>
</p>

<p>
  <b>Total:</b>
  <%= @order.total %>
</p>


<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>